export enum DFromClientEvent {
  AddCustomLobby = "AddCustomLobby_Client",
  AddMapToVoting = "AddMapToVoting_Client",
  CloseMapMenu = "CloseMapMenu_Client",
  LeaveCustomLobbyMenu = "LeaveCustomLobbyMenu_Client",
  LoadAllCustomLobbies = "LoadAllCustomLobbies_Client",
  LoadFavoriteMaps = "LoadFavoriteMaps_Client",
  LoadLanguage = "LoadLanguage_Client",
  LoadMapVoting = "LoadMapVoting_Client",
  LoadOrders = "LoadOrders_Client",
  OpenMapMenu = "OpenMapMenu_Client",
  RemoveCustomLobby = "RemoveCustomLobby_Client",
  ResetMapVoting = "ResetMapVoting_Client",
  SetMapVotes = "SetMapVotes_Client",
  SyncAllCustomLobbies = "SyncAllCustomLobbies_Client",
  ToggleChatOpened = "ToggleChatOpened_Client",
  ToggleFreeroam = "ToggleFreeroam_Client",
  ToggleInFightLobby = "ToggleInFightLobby_Client",
  ToggleLobbyChoice = "ToggleLobbyChoice_Client",
  ToggleMapCreator = "ToggleMapCreator_Client",
  ToggleTeamOrderModus = "ToggleTeamOrderModus_Client",
}
