export enum DToClientEvent {
  AddMapVote = "AddMapVote_Browser",
  ChooseArenaToJoin = "ChooseArenaToJoin_Browser",
  ChooseMapCreatorToJoin = "ChooseMapCreatorToJoin_Browser",
  CloseMapVotingMenu = "CloseMapVotingMenu_Browser",
  CreateCustomLobby = "CreateCustomLobby_Browser",
  GetCurrentPositionRotation = "GetCurrentPositionRotation_Browser",
  GetVehicle = "GetVehicle_Browser",
  JoinCustomLobby = "JoinCustomLobby_Browser",
  JoinCustomLobbyWithPassword = "JoinCustomLobbyWithPassword_Browser",
  JoinedCustomLobbiesMenu = "JoinedCustomLobbiesMenu_Browser",
  LeftCustomLobbiesMenu = "LeftCustomLobbiesMenu_Browser",
  LanguageChange = "LanguageChange_Browser",
  // RemoveMapVote = "RemoveMapVote_Browser",
  TeleportToPositionRotation = "TeleportToPositionRotation_Browser",
  TeleportToXY = "TeleportToXY_Browser",
  ToggleMapFavorite = "ToggleMapFavorite_Browser",
  SaveMapCreatorData = "SaveMapCreatorData_Browser",
  SendMapCreatorData = "SendMapCreatorData_Browser",
  LoadMySavedMap = "LoadMySavedMap_Browser",
  LoadMySavedMapNames = "LoadMySavedMapNames_Browser",

  AddMapCreatorPosition = "AddMapCreatorPosition_Browser",
  RemoveMapCreatorPosition = "RemoveMapCreatorPosition_Browser"
}
