enum ScaleformFunction {
    SHOW_SHARD_WASTED_MP_MESSAGE = "SHOW_SHARD_WASTED_MP_MESSAGE",
    INSTRUCTIONAL_BUTTONS = "INSTRUCTIONAL_BUTTONS",
    SHARD_ANIM_OUT = "SHARD_ANIM_OUT",
    SHOW_MIDSIZED_MESSAGE = "SHOW_MIDSIZED_MESSAGE",
    SHOW_PLANE_MESSAGE = "SHOW_PLANE_MESSAGE",
    SHOW_SHARD_CENTERED_MP_MESSAGE = "SHOW_SHARD_CENTERED_MP_MESSAGE",
    SHOW_SHARD_MIDSIZED_MESSAGE = "SHOW_SHARD_MIDSIZED_MESSAGE",
    SHOW_WASTED_MP_MESSAGE = "SHOW_WASTED_MP_MESSAGE",
    SHOW_WEAPON_PURCHASED = "SHOW_WEAPON_PURCHASED",

    TRANSITION_OUT = "TRANSITION_OUT"
}

export default ScaleformFunction;
