export interface Language {
    MapVoting: string;
    MapCreator: string;
    All: string;
    Normal: string;
    Bomb: string;
    Favourites: string;
    Voting: string;
    Vote: string;
    Creator: string;
    Name: string;
    German: string;
    English: string;
    MapSettings: string;
    Description: string;
    Type: string;
    TeamSpawns: string;
    MapLimit: string;
    MapCenter: string;
    BombPlaces: string;
    NumberShort: string;
    Remove: string;
    AddPos: string;
    Teleport: string;
    MapCenterInfo: string;
    MinPlayers: string;
    MaxPlayers: string;
    CouldNotDeserialize: string;
    NameAlreadyExists: string;
    Unknown: string;
    Cooldown: string;
    MapCreatedSuccessfully: string;
    SavedMapLoadSuccessful: string;

    ATTACK: string;
    BACK: string;
    SPREAD_OUT: string;
    TO_BOMB: string;
}
