enum ToServerEvent {
    AcceptInvitation = "c1",
    AcceptTDSTeamInvitation = "c67",
    AddRatingToMap = "c2",
    AnswerToOfflineMessage = "c3",

    BuyMap = "c4",

    CancelCharCreateData = "c69",
    ChooseTeam = "c6",
    CommandUsed = "c7",
    CreateCustomLobby = "c8",

    DeleteOfflineMessage = "c9",

    FromBrowserEvent = "c64",

    GangCommand = "c76",
    GetSupportRequestData = "c10",
    GetVehicle = "c11",
    GotHit = "c12",

    JoinedCustomLobbiesMenu = "c14",
    JoinLobby = "c15",
    JoinLobbyWithPassword = "c16",

    LanguageChange = "c18",
    LeaveLobby = "c19",
    LeftCustomLobbiesMenu = "c20",
    LeftSupportRequest = "c21",
    LeftSupportRequestsList = "c22",
    LoadAllMapsForCustomLobby = "c65",
    LoadApplicationDataForAdmin = "c24",
    LoadDatasForCustomLobby = "c66",
    LoadGangWindowData = "c75",
    LoadMapForMapCreator = "c25",
    LoadMapNamesToLoadForMapCreator = "c26",
    LoadPlayerWeaponStats = "c72",
    LoadUserpanelData = "c27",
    LobbyChatMessage = "c23",
    LogMessageToServer = "c77",
    LogExceptionToServer = "c78",
    MapCreatorStartNewMap = "c28",
    MapCreatorSyncCurrentMapToServer = "c17",
    MapCreatorSyncData = "c30",
    MapCreatorSyncLastId = "c31",
    MapCreatorSyncNewObject = "c32",
    MapCreatorSyncObjectPosition = "c33",
    MapCreatorSyncRemoveObject = "c34",
    MapCreatorSyncRemoveTeamObjects = "c5",
    MapsListRequest = "c35",
    MapVote = "c36",

    OutsideMapLimit = "c37",

    RejectInvitation = "c38",
    RejectTDSTeamInvitation = "c68",
    RemoveMap = "c39",
    RequestPlayersForScoreboard = "c40",

    SaveCharCreateData = "c29",
    SaveMapCreatorData = "c41",
    SavePlayerCommandsSettings = "c70",
    SaveSettings = "c42",
    SaveSpecialSettingsChange = "c43",
    SendApplication = "c44",
    SendApplicationInvite = "c45",
    SendMapCreatorData = "c46",
    SendMapRating = "c47",
    SendOfflineMessage = "c48",
    SendSupportRequest = "c49",
    SendSupportRequestMessage = "c50",
    SendTeamOrder = "c51",
    SetInFreecam = "c13",
    SetSupportRequestClosed = "c52",
    SpectateNext = "c53",
    StartDefusing = "c54",
    StartPlanting = "c55",
    StopDefusing = "c56",
    StopPlanting = "c57",
    SuicideKill = "c58",
    SuicideShoot = "c59",

    ToggleCrouch = "c60",
    ToggleMapFavouriteState = "c61",
    TryLogin = "c62",
    TryRegister = "c63",

    WeaponShot = "c71",
    WeaponSwitch = "c79",
}

export default ToServerEvent;
