export enum LobbySetting {
    LobbyId = 0,
    Name,
    OwnerName,
    Password,
    StartHealth,
    StartArmor,
    AmountLifes,
    MixTeamsAfterRound,
    ShowRanking,
    BombDetonateTimeMs,
    BombDefuseTimeMs,
    BombPlantTimeMs,
    RoundTime,
    CountdownTime,
    SpawnAgainAfterDeathMs,
    MapLimitTime,
    MapLimitType,
    Teams,
    Maps,
    Weapons
}
