enum InputGroup {
    Move,
    Look,
    Wheel,
    Cellphone_Navigate,
    Cellphone_Navigate_UD,
    Cellphone_Navigate_LR,
    Frontend_DPad_All,
    Frontend_DPad_UD,
    Frontend_DPad_LR,
    Frontend_LStick_All,
    Frontend_RStick_All,
    Frontend_Generic_UD,
    Frontend_Generic_LR,
    Frontend_Generic_All,
    Frontend_Bumpers,
    Frontend_Triggers,
    Frontend_Sticks,
    Script_DPad_All,
    Script_DPad_UD,
    Script_DPad_LR,
    Script_LStick_All,
    Script_RStick_All,
    Script_Bumpers,
    Script_Triggers,
    Weapon_Wheel_Cycle,
    Fly,
    Sub,
    Veh_Move_All,
    Cursor,
    Scroll,
    Sniper_Zoom_Secondary,
    Veh_Hydraulics_Control
}

export default InputGroup;
