export enum UserpanelNavPage {
    Main,
    MyStats,
    Admin,
    Settings,
    Commands,
    CommandsUser,
    CommandsTDSTeam,
    CommandsDonator,
    CommandsVIP,
    CommandsLobbyOwner,
    Rules,
    RulesUser,
    RulesTDSTeam,
    RulesVIP,
    FAQ,
    Reports,
    Applications
}
