export enum DToClientEvent {
  AddMapVote = "AddMapVote_Browser",
  ChooseArenaToJoin = "ChooseArenaToJoin_Browser",
  ChooseMapCreatorToJoin = "ChooseMapCreatorToJoin_Browser",
  CloseMapVotingMenu = "CloseMapVotingMenu_Browser",
  CloseUserpanel = "CloseUserpanel_Browser",
  CreateCustomLobby = "CreateCustomLobby_Browser",
  GetHashedPassword = "GetHashedPassword_Browser",
  GetVehicle = "GetVehicle_Browser",
  HoldMapCreatorObject = "HoldMapCreatorObject_Browser",
  InputStarted = "InputStarted_Browser",
  InputStopped = "InputStopped_Browser",
  JoinCustomLobby = "JoinCustomLobby_Browser",
  JoinCustomLobbyWithPassword = "JoinCustomLobbyWithPassword_Browser",
  JoinedCustomLobbiesMenu = "JoinedCustomLobbiesMenu_Browser",
  LanguageChange = "LanguageChange_Browser",
  LeftCustomLobbiesMenu = "LeftCustomLobbiesMenu_Browser",
  // RemoveMapVote = "RemoveMapVote_Browser",
  MapCreatorHighlightPos = "MapCreatorHighlightPos_Browser",
  MapCreatorStartNew = "MapCreatorStartNew_Browser",
  MapCreatorStartObjectChoice = "MapCreatorStartObjectChoice_Browser",
  MapCreatorStopObjectPreview = "MapCreatorStopObjectPreview_Browser",
  MapCreatorStartVehicleChoice = "MapCreatorStartVehicleChoice_Browser",
  MapCreatorStopVehiclePreview = "MapCreatorStopVehiclePreview_Browser",
  OnColorSettingChange = "OnColorSettingChange_Browser",
  RemoveMapCreatorPosition = "RemoveMapCreatorPosition_Browser",
  RemoveMapCreatorTeamNumber = "RemoveMapCreatorTeamNumber_Browser",
  TeleportToPositionRotation = "TeleportToPositionRotation_Browser",
  ToggleMapFavorite = "ToggleMapFavorite_Browser",
  SaveMapCreatorData = "SaveMapCreatorData_Browser",
  SendMapCreatorData = "SendMapCreatorData_Browser",
  StartMapCreatorPosPlacing = "StartMapCreatorPosPlacing_Browser",

}
