export enum DToServerEvent {
    AcceptInvitation = "AcceptInvitation_Browser",
    AnswerToOfflineMessage = "AnswerToOfflineMessage_Browser",
    BuyMap = "BuyMap_Browser",
    ChooseTeam = "ChooseTeam_Browser",
    DeleteOfflineMessage = "DeleteOfflineMessage_Browser",
    GetSupportRequestData = "GetSupportRequestData_Browser",
    LeaveLobby = "LeaveLobby_Browser",
    LeftSupportRequest = "LeftSupportRequest_Browser",
    LeftSupportRequestsList = "LeftSupportRequestsList_Browser",
    LoadApplicationDataForAdmin = "LoadApplicationDataForAdmin_Browser",
    LoadMapNamesToLoadForMapCreator = "LoadMapNamesToLoadForMapCreator_Browser",
    LoadMapForMapCreator = "LoadMapForMapCreator_Browser",
    LoadUserpanelData = "LoadUserpanelData_Browser",
    RejectInvitation = "RejectInvitation_Browser",
    RemoveMap = "RemoveMap_Browser",
    SaveSettings = "SaveSettings_Browser",
    SendApplication = "SendApplication_Browser",
    SendApplicationInvite = "SendApplicationInvite_Browser",
    SendOfflineMessage = "SendOfflineMessage_Browser",
    SendSupportRequest = "SendSupportRequest_Browser",
    SendSupportRequestMessage = "SendSupportRequestMessage_Browser",
    SetSupportRequestClosed = "SetSupportRequestClosed_Browser",

    FromBrowserEvent = "FromBrowserEvent_Browser"
}
