export enum DToServerEvent {
    AcceptInvitation = "c1",
    AnswerToOfflineMessage = "c3",
    BuyMap = "c4",
    ChooseTeam = "c6",
    DeleteOfflineMessage = "c9",
    GetSupportRequestData = "c10",
    LeaveLobby = "c19",
    LeftSupportRequest = "c21",
    LeftSupportRequestsList = "c22",
    LoadApplicationDataForAdmin = "c24",
    LoadMapNamesToLoadForMapCreator = "c26",
    LoadMapForMapCreator = "c25",
    LoadUserpanelData = "c27",
    MapCreatorSyncData = "c30",
    RejectInvitation = "c38",
    RemoveMap = "c39",
    SaveSettings = "c42",
    SaveSpecialSettingsChange = "c43",
    SendApplication = "c44",
    SendApplicationInvite = "c45",
    SendOfflineMessage = "c48",
    SendSupportRequest = "c49",
    SendSupportRequestMessage = "c50",
    SetSupportRequestClosed = "c52",

    FromBrowserEvent = "c64"
}
